layout_spectrum: 0.7363051
color:
  saturation: 0
  lightness: 0
  brandStrength: 0.9865735
  brandColors:
    - '#0D0D0D'
    - '#C6C6C6'
    - '#656565'
  rhythmicContrast: 0.150913
typography_spectrum: 0.9357216
name: nosaudio
